name: Release

on:
  push:
    tags:
      - v*
    branches: [ main ]

jobs:

  build:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18
        id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
    #     go get -v -t -d ./...
    #     curl -o tanzu https://storage.googleapis.com/tanzu-cli/artifacts/core/latest/tanzu-core-linux_amd64 && \
    #         mv tanzu /usr/local/bin/tanzu && \
    #       chmod +x /usr/local/bin/tanzu
    #     tanzu plugin repo add -b tanzu-cli-admin-plugins -n admin
      run: |
        curl -L -o tanzu-cli-linux-amd64.tar.gz https://github.com/vmware-tanzu/tanzu-cli/releases/download/v0.90.0-alpha.0/tanzu-cli-linux-amd64.tar.gz && \
          mkdir -p tanzu && \
          tar xvzf tanzu-cli-linux-amd64.tar.gz -C tanzu
        sudo install tanzu/v0.90.0-alpha.0/tanzu-cli-linux_amd64 /usr/local/bin/tanzu
        tanzu ceip-participation set false
        tanzu init
        tanzu version
        tanzu plugin install builder
        tanzu plugin install test
        tanzu plugin list

    # - name: init
    #   run: make init

    # - name: Lint
    #   run: make lint

    - name: Test
      run: make test

    - name: Build
      run: |
        tanzu version
        tanzu plugin list
        make plugin-build

    # - id: upload-cli-artifacts
    #   uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
    #   with:
    #     path: ./artifacts
    #     destination: accelerator-plugin
    #     credentials: ${{ secrets.GCP_BUCKET_SA }}
